{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "microservice.fullname" . }}
  labels:
    app: {{ template "microservice.name" . }}
    chart: {{ template "microservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.httpPort | default 3000 }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "microservice.name" . }}
    release: {{ .Release.Name }}
{{- end }}